apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-angelambd-dev
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: stedi-angelambd-dev
  template:
    metadata: 
      labels:
        app: stedi-angelambd-dev
    spec:
      containers:
        - name: stedi-angelambd-dev
          image: gcr.io/gurlpower/ange-stedi-api
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: redis-secrets-prod
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests: 
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: stedi-angela-nodeport
spec:
  selector:
    app: stedi-angelambd-dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-angela-certificate
spec:
  domains:
    - angeladomingo.cit262.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-angela-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-angela-public
    networking.gke.io/managed-certificates: stedi-angela-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-angela-nodeport
            port:
              number: 80