apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-angela
spec:
  selector:
    matchLabels: 
      app: redis-stedi-angela # must match spec.template.metadata.labels
  serviceName: redis-stedi-angela
  replicas: 1
  template:
    metadata: 
      labels:
        app: redis-stedi-angela
    spec:
      containers:
        - name: redis-stedi-angela
          image: redis:7.0.5-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "${REDIS_PASS}", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-angela
                  key: REDIS_PASS
          volumeMounts:
            - name: redis-angela-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata: 
      name: redis-angela-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stedi-angela
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-stedi-angela